### ISSUE TITLE
書いて欲しい橫假名

### ISSUE THREAD

**Issue by ne-sachirou** [ne-sachirou/c4se-web#12]
**目的：**
橫假名の規格 ( http://c4se.jp/yoko_kana/standard ) に載せる例が欲しい。

**方針：**
- 橫假名を知らない人が勉強できる充分な資料と成る。
- 流麗さよりも造がわかりやすいやうにし、美しさを兼ね備える。

**書くべきもの：**
「あ」～「ん」の
1. 孤立形
2. 語頭-語中-語尾の続け書き
3. 例となる語

「が」「ゔ」「ぱ」の
1. 孤立形
2. 語頭-語中-語尾の続け書き

「ゃ」「ゅ」「ょ」「ぁ」の
1. 孤立形
2. 例となる語

促音・長音・外来語符の
1. 例となる語

サ變合字の
1. 孤立形
2. 例となる語

**作業法：**
- [ ] 書いて画像にするフローを実験して決める。

---

**ア〜ン**
- [ ] ア
- [ ] アアア
- [ ] イ
- [ ] イイイ
- [ ] ウ
- [ ] ウウウ
- [ ] エ
- [ ] エエエ
- [ ] オ
- [ ] オオオ
- [ ] カ
- [ ] カカカ
- [ ] キ
- [ ] キキキ
- [ ] ク
- [ ] ククク
- [ ] ケ
- [ ] ケケケ
- [ ] コ
- [ ] コココ
- [ ] サ
- [ ] サササ
- [ ] シ
- [ ] シシシ
- [ ] ス
- [ ] ススス
- [ ] セ
- [ ] セセセ
- [ ] ソ
- [ ] ソソソ
- [ ] タ
- [ ] タタタ
- [ ] チ
- [ ] チチチ
- [ ] ツ
- [ ] ツツツ
- [ ] テ
- [ ] テテテ
- [ ] ト
- [ ] トトト
- [ ] ナ
- [ ] ナナナ
- [ ] ニ
- [ ] ニニニ
- [ ] ヌ
- [ ] ヌヌヌ
- [ ] ネ
- [ ] ネネネ
- [ ] ノ
- [ ] ノノノ
- [ ] ハ
- [ ] ハハハ
- [ ] ヒ
- [ ] ヒヒヒ
- [ ] フ
- [ ] フフフ
- [ ] ヘ
- [ ] ヘヘヘ
- [ ] ホ
- [ ] ホホホ
- [ ] マ
- [ ] マママ
- [ ] ミ
- [ ] ミミミ
- [ ] ム
- [ ] ムムム
- [ ] メ
- [ ] メメメ
- [ ] モ
- [ ] モモモ
- [ ] ヤ
- [ ] ヤヤヤ
- [ ] ユ
- [ ] ユユユ
- [ ] ヨ
- [ ] ヨヨヨ
- [ ] ラ
- [ ] ラララ
- [ ] リ
- [ ] リリリ
- [ ] ル
- [ ] ルルル
- [ ] レ
- [ ] レレレ
- [ ] ロ
- [ ] ロロロ
- [ ] ワ
- [ ] ワワワ
- [ ] ヰ
- [ ] ヰヰヰ
- [ ] 𛀁
- [ ] 𛀁𛀁𛀁
- [ ] ヲ
- [ ] ヲヲヲ
- [ ] ン
- [ ] ンンン

**ア〜ン語頭**
無線局運用規則　別表第五号　和文通話表より。
- [ ] アサヒ
- [ ] イロハ
- [ ] ウヘノ
- [ ] エイゴ
- [ ] オホサカ
- [ ] カハセ
- [ ] キッテ
- [ ] クラブ
- [ ] ケシキ
- [ ] コドモ
- [ ] サクラ
- [ ] シンブン
- [ ] スズメ
- [ ] セカイ
- [ ] ソロバン
- [ ] タバコ
- [ ] チドリ
- [ ] ツルカメ
- [ ] テガミ
- [ ] トウキャウ
- [ ] ナゴヤ
- [ ] ニッポン
- [ ] ヌマヅ
- [ ] ネズミ
- [ ] ノハラ
- [ ] ハガキ
- [ ] ヒカウキ
- [ ] フジサン
- [ ] ヘイワ
- [ ] ホケン
- [ ] マッチ
- [ ] ミカサ
- [ ] ムセン
- [ ] メイヂ
- [ ] モミヂ
- [ ] ヤマト
- [ ] ユミヤ
- [ ] エド
- [ ] ヨシノ
- [ ] ラジオ
- [ ] リンゴ
- [ ] ルスヰ
- [ ] レンゲ
- [ ] ローマ
- [ ] ワラビ
- [ ] ヰド
- [ ] ヱマキ
- [ ] ヲハリ
- [ ] ンクルマ

**ア〜ン語中・語尾**
未決

**サ変**
「ザレル」は無し。
- [ ] キョカ　セズ
- [ ] キョカ　シツツ
- [ ] キョカ　ス
- [ ] キョカ　スルトキ
- [ ] キョカ　スレドモ
- [ ] キョカ　セヨ
- [ ] キョカ　サレル
- [ ] キョカ　シロ
- [ ] キン　ゼズ
- [ ] キン　ジツツ
- [ ] キン　ズ
- [ ] キン　ズルトキ
- [ ] キン　ズレドモ
- [ ] キン　ゼヨ
- [ ] キン　ジロ

**濁音**
- [ ] ヴェール
- [ ] イガク
- [ ] カスガ

**半濁音**
- [ ] パール
- [ ] ルピー
- [ ] アンプ

**拗音**
- [ ] シャリ
- [ ] ギルガメシュ
- [ ] キョリ
- [ ] ファン

**促音**
- [ ] ヨット
- [ ] キップ

**長音**
- [ ] カード
- [ ] カレー

**外語符**
未決

**Comment by HarunaT** [comment]
橫假名書例に良からうと思ふ物を以下にずらずら竝べる。

| 孤立 | 連続 | 語頭 | 語中 | 語尾 |
| --- | --- | --- | --- | --- |
| ア | アアア | アサヒ | キアヒ | ロウア |
| イ | イイイ | イロハ | タイガ | ミライ |
| ウ | ウウウ | ウヘノ | トウア | リヨウ |
| エ | エエエ | エイゴ | リエン | アロエ |
| オ | オオオ | オホサカ | キオク | パラオ |

以下語例のみ

```
カハセ     サカヒ     ツイカ
キッテ     ベキラ     カワキ
クラブ     タクミ     バイク
ケシキ     イケス     ミカケ
コドモ     マコモ     イレコ

サクラ     アサリ     アヅサ
シンブン   ハシラ     サラシ
スズメ     ナスビ     ナカス
セカイ     ヤセイ     ヨミセ
ソロバン   サソリ     ゲンソ

タバコ     ワタシ     アナタ
チドリ     マチヤ     カハチ
ツルカメ   ケツギ     アイツ
テガミ     ヨテイ     ハヤテ
トウキャウ サトリ     テイト

ナゴヤ     ミナモ     カヒナ
ニッポン   アニキ     コゼニ
ヌマヅ     カヌチ     アイヌ
ネズミ     コネコ     アカネ
ノハラ     イノリ     ピアノ

ハガキ     イハホ     サニハ
ヒカウキ   アヒダ     ユフヒ
フジサン   アフヒ     ワリフ
ヘイワ     キヘイ     カナヘ
ホケン     イホリ     タリホ

マッチ     ヤマヒ     サンマ
ミカサ     スミレ     アユミ
ムセン     ネムロ     ニンム
メイヂ     カメラ     スルメ
モミヂ     ヰモリ     マリモ

ヤマト     モヤシ     クリヤ
ユミヤ     ミユキ     セキユ
エド       モエギ     キノエ
ヨシノ     コヨリ     ウキヨ

ラジオ     アラシ     ミヅラ
リンゴ     トリヰ     ノコリ
ルスヰ     イルカ     タオル
レンゲ     ハレギ     ミゾレ
ローマ     ヰロリ     クシロ

ワラビ     イワウ     クルワ
ヰド       アヰゾメ   アヂサヰ
ヱマキ     ユヱン     スミヱ
ヲハリ     トヲカ     マスラヲ
ンクルマ   アンピ     エイヱン
```

ガギグゲゴ
ガヨク イガク カスガ
ヴルスト アヴァ アーヴ

パピプペポ
パール ルピー アンプ

ャ ュ ョ ァ
シャリ リュウ キョリ ファン

ッ
ヨット キップ ニッチ

ー
カード キープ ルール

εモサプリド クエンサン エン
εメチルフェニデート エンサン エン

| 1 | 2 | 3 |
| --- | --- | --- |
| せ | キョカ せズ | キン ぜズ |
| し | キョカ しツツ | キン じツツ |
| す | キョカ す | キン ず |
| する | キョカ するトキ | キン ずるトキ |
| すれ | キョカ すれドモ | キン ずれドモ |
| せよ | キョカ せよ | キン ぜよ |
| さ | キョカ さレル | キン ざレル |
| しろ | キョカ しろ | キン じろ |

**Comment by ne-sachirou** [comment]
キアヒ ロウア リエン 等あまり適切で無い例が紛れてゐるやうに感じるが、それより前にア アアア アサヒ キアヒ ロウアの画像だけみてみたい。

そも、なにがふさはしいか決めるのが先ぢゃの？

**Comment by HarunaT** [comment]
夜勤明けの惚けた腦から捻り出した爲に一部不適な語が混入した事を御詫びする。
取り敢ず圖像。
![ykgnthn-kari01](https://cloud.githubusercontent.com/assets/12173743/8508360/e89f5512-22a7-11e5-9a19-ea7c1f405a6c.JPG)
鉛筆書きなので書き直す事が出來る。

不適な語の置換案
キアヒ→シアン
ロウア→ハクア
リエン→アエン
ナカス (中洲の積りだったが泣かすに見ゆ)→アイス
アニキ→ユニフ
サニハ→
クルワ→ハニワ
スミヱ→タウヱ

**Comment by HarunaT** [comment]
畫像が大き過ぎた。

**Comment by ne-sachirou** [comment]
議事録
https://docs.google.com/document/d/1QQk2Ulq_T_O-RV-gbLqZmj9_dq2UNCayZQI-2-3p6Mo/edit?usp=sharing

**Comment by HarunaT** [comment]
取り敢ず實驗の生データを上載す。此れらの内適當な物を加工して行く。
カラー
https://www.dropbox.com/s/mtaw1k357q6hfhc/scan-jikken01-colour.tiff?dl=0
グレスケ
https://www.dropbox.com/s/rennmxrw19g8nu8/scan-jikken01-grey.tiff?dl=0
二値
https://www.dropbox.com/s/zmwq98qxi0wbapz/scan-jikken01-bi.tiff?dl=0
因みにTIFFって貼れないの？

**Comment by ne-sachirou** [comment]
Slackでやれ
