### ISSUE TITLE
縦ラテンサイト制作議論

### ISSUE THREAD

**Issue by ne-sachirou** [ne-sachirou/c4se-web#16]

**Comment by HarunaT** [comment]
縱ラテンフォントの設計
含む文字(Latin-1輯錄文字の部分集合)
　聯綿字
　　a-z, (ß), à, á, â, ã, ä, å, æ, ç, è, é, ê, ë, ì, í, î, ï, (ð), ñ, ò, ó, ô, õ, ö, ø, ù, ú, û, ü, ý, (þ), ÿ
　非聯綿字
　　符號値20-2F, 3A-40, 5B-60, 7B-7E, A0-BF, D7, F7
　數字
　　0-9

未定
　大文字の處遇。
　記號の内、優先的に作る物・餘力が有れば作る物・作らない物

**Comment by HarunaT** [comment]
大文字はどうしませう。

**Comment by ne-sachirou** [comment]
[Latin-1](https://ja.wikipedia.org/wiki/ISO/IEC_8859-1)
大文字は小文字と区別しないでよいとおもふ。
Þþはだうしやうか。thかな。
ÐØø  はだう表記することにしてたっけ。
あとは合字でつくれさうだね。
記号類はなにかフリー (自由) なフォントのコピーでもよいよ。
数字は未定。頑張れれば文字を作るかも。何を参考にすれば好いかな…。作れなかった場合は、アラビア文字をそのまま使う or 漢数字を入れる。

**Comment by ne-sachirou** [comment]
![1452609597946](https://cloud.githubusercontent.com/assets/452772/12327028/89d05cee-bb17-11e5-99db-d9b916bc7e82.jpg)
![1452610657181](https://cloud.githubusercontent.com/assets/452772/12327032/8d028cac-bb17-11e5-8673-49656feb3ffa.jpg)
![1452610661367](https://cloud.githubusercontent.com/assets/452772/12327036/8f93d8f4-bb17-11e5-8161-53bd0140d6c9.jpg)
![1452728293112](https://cloud.githubusercontent.com/assets/452772/12327038/91a06b8a-bb17-11e5-9173-e5af24666d90.jpg)
![1](https://cloud.githubusercontent.com/assets/452772/12327061/a8f9f0ee-bb17-11e5-989a-af912d7749c8.png)

**Comment by ne-sachirou** [comment]
[SIL Open Font License](https://ja.wikipedia.org/wiki/SIL_Open_Font_License)
[GPLフォント例外](https://ja.wikipedia.org/wiki/GPL%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E4%BE%8B%E5%A4%96)

※Licenseに注意
[DaFont - Download fonts](http://www.dafont.com/)
[1001 Free Fonts - Download Fonts](http://www.1001freefonts.com/)
[1001 Fonts · Free Fonts Baby!](http://www.1001fonts.com/)
[28,390 free fonts for Windows and Mac - FontSpace](http://www.fontspace.com/)

**Comment by HarunaT** [comment]
最新の開發中の版。a, b, qを含む。
[VLatin20160113.sfd.zip](https://github.com/ne-sachirou/c4se-web/files/92107/VLatin20160113.sfd.zip)

**Comment by HarunaT** [comment]
最新の開發中の版。a-j, n-q, t, u, w, y, z を含む。
k, l, m, r, s, v, xは未。
[VLatin20160117.sfd.zip](https://github.com/ne-sachirou/c4se-web/files/93443/VLatin20160117.sfd.zip)

**Comment by ne-sachirou** [comment]
記号は自由な字體から合成。字體は @ne-sachirou が探す
Ççは、Cの右に小さなZを中心線から離して置く
Ææは、AとEの自然な合字
字體は表示が潰れがちだが、大きめに表示する運用で回避。余裕があれば改造
今週中にA-Zの26文字はできるね ([応募締め切りは2/8](http://tategaki.github.io/awards/))
Web: 序文、規格、縦Latin Webページ製作法解説、改訂プロセス、書例、御樂しみ
御樂しみ: 縦ラテン画像をTweetする奴作るよ

**懸案事項:**
Ðð (収録しないかも。Dの変形)
Øø (収録しないかも。OとEの合字)
Þþ (収録しないかも)
ß (SとZの合字にしたい)
數字

**Comment by HarunaT** [comment]
ににに

**Comment by HarunaT** [comment]
r,v,x以外を含む。幾つかの文字は修正を受けた。
[VLatin20160120.sfd.zip](https://github.com/ne-sachirou/c4se-web/files/96336/VLatin20160120.sfd.zip)

**Comment by HarunaT** [comment]
a-z, hyphenを含む。今後字閒調整の爲の字形調整、字閒調整機構の實裝を豫定。
[VLatin20160120-2.sfd.zip](https://github.com/ne-sachirou/c4se-web/files/96932/VLatin20160120-2.sfd.zip)

**Comment by ne-sachirou** [comment]
[Slack](https://c4se.slack.com)に移行
