### ISSUE TITLE
[yUraru] 辭書システムを作るまでの仮の語彙記述形式を決める

### ISSUE THREAD

**Issue by ne-sachirou** [ne-sachirou/c4se-web#30]
ストーリーポイント:1
辭書システムを作るまでの @HarunaT の便利の爲

**Comment by ne-sachirou** [comment]
[yUraru辭書仮置き場](https://docs.google.com/spreadsheets/d/1on3Y8fRQsBfRRQ_YbkpRnsAY8_xaR42ErCuKA9QSLZo/edit?usp=sharing)

**Comment by HarunaT** [comment]
👍LGTM
![](https://media.giphy.com/media/xoJd2X5rG8oAE/giphy.gif)

**Comment by ne-sachirou** [comment]
DONE
