### ISSUE TITLE
Logoを新生する

### ISSUE THREAD

**Issue by ne-sachirou** [ne-sachirou/c4se-web#7]
古いlogoは使ひものにならぬので…。faviconにも使ふ。
- [x] Logo designの指針を決める。 https://github.com/ne-sachirou/c4se-web/issues/7#issuecomment-105008631
- [ ] Logoを作る。

c4se 序文

> ようこそc4seへ。現在では三人のメンバーがc4seでは活動してゐます。c4seは、その中で幾つかのプロジェクトを活動させるためのラック (Rack) です。現在は四つのプロジェクトが活動してゐます。メンバーの個々はそれぞれの個別のプロジェクトを他に持ってゐます。さういった個別なメンバーが、協調せずに勝手に活動できるやうにするためのラックとしてここは存在します。
> 團結力、貢獻、熱意、共同性。これらの通常プロジェクトに必要だとみなされてゐる非人閒的な〈槪念1〉は、c4seとは最も緣遠いものです。矛盾、裏切り、孤獨、原個人。これら〈槪念2〉で活動する實驗場としてここは存在します。

“c4se” の由来: “bird” をひとつづつずらした。

Old logos below.

c4se 1
![c4se_1](https://cloud.githubusercontent.com/assets/452772/7642573/04392da0-facd-11e4-82da-de1fbf147622.png)

c4se 2
![c4se_2](https://cloud.githubusercontent.com/assets/452772/7642575/0c82bf1c-facd-11e4-9eb3-f6ea0825028a.png)

**Comment by HarunaT** [comment]
按・其の一
![image](https://cloud.githubusercontent.com/assets/12173743/7663719/b20c0492-fbaa-11e4-8ce9-07eeb50d0087.png)

**Comment by HarunaT** [comment]
按・其の一
![c4seneu04](https://cloud.githubusercontent.com/assets/12173743/7663726/e36688aa-fbaa-11e4-8e87-63c13bc1592c.png)

**Comment by HarunaT** [comment]
案・其の二
![c4seneu05](https://cloud.githubusercontent.com/assets/12173743/7664173/3ec691f8-fbb6-11e4-89a2-a57555d123ab.png)

**Comment by HarunaT** [comment]
案・其の二 (ふたへ版) (此れは鳥の如くにも見ゆ)
![c4seneu05dash](https://cloud.githubusercontent.com/assets/12173743/7664179/7e9b09e4-fbb6-11e4-8c59-b5c6ee26c544.png)

**Comment by ne-sachirou** [comment]
@HarunaT 案・其の二はとてもよいのですが、型に嵌まり過ぎてゐる気がする。ふむ。

**Comment by ne-sachirou** [comment]
_[このコメントを編集せよ]_
**指針**
- 不規則さ
- 不適合さ
- 抽象性

**制約**
- 判讀できる必要は無し
- 16px × 16px で判別することを考慮せよ (もっと大きなサイズでも勿論使ふ)
- 背景は白 (透過) が基本だが、背景白でも黒でも使へるやうにする。

**Comment by HarunaT** [comment]
色を付けてないけど、
![c4sebird](https://cloud.githubusercontent.com/assets/12173743/7697036/b067e070-fe3e-11e4-863c-5ffa19d269fc.png)
こんなの出來た。16px × 16px c4se で鳥を象る。
不規則さと不適合さには劣るかもしれない。

**Comment by ne-sachirou** [comment]
大変良い案だが、今回の目的には具象的に過ぎる気がする。

@HarunaT @lotus-gate 私も案を設計してみた。
![img00697](https://cloud.githubusercontent.com/assets/452772/7787805/def0968e-0259-11e5-9451-bed03e656895.jpg)
![img00700](https://cloud.githubusercontent.com/assets/452772/7787807/e5a89440-0259-11e5-889b-1b81cf300801.jpg)
上部は水滴型。色は深緑と真っ赤。背景は白。曲がった植物様。c, 4, s, eのどの文字も強調しがたいので、すべての文字を含ませた。

**Comment by lotus-gate** [comment]
![c4se](https://cloud.githubusercontent.com/assets/12562572/7789364/f0917e00-0298-11e5-8f45-fc849cf06d87.png)
ほらよ( ,,Ծ ◡ Ծ,,)

**Comment by ne-sachirou** [comment]
赤は明る過ぎ? 線は同じ太さぢゃなくてゆるやかに太さを変へていったはうがよささう。下はもっと長目。

**Comment by HarunaT** [comment]
良い設計案と思ふ。近く Illustrator で淨書を試みんとす。

**Comment by ne-sachirou** [comment]
Slackでやれ
